### ISSUE TITLE
organismsコンポーネントに対してPR、Push時に自動テストが走るようにする

### ISSUE THREAD

**Issue by TaiyoMaruyama** [TaiyoMaruyama/population-trend-graph#42]
## 概要

`test-atoms.yml`ファイルを修正
`test-components.yml`にファイル名を修正して、`organisms/`配下にも自動テストが走るように設定。

## やること
```yml
 - run: npm run build --if-present
 - run: npm run test:atoms
 - run: npm run test:molecules
 - run: npm run test:organisms // ←追記
```
